### PR TITLE
chore: add commonJS support

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
@zcesur, kindly take a look at this and lemme know if I'm on the right track.

### CODE REVIEW

**Comment by zcesur** [comment]
thanks caleb, can you `npm install @algora/sdk@v0.1.3-beta.0` to see if this resolved your issue?

**Comment by kaf-lamed-beyt** [comment]
Awesome! I'll do this and let you know how it goes.

**Comment by kaf-lamed-beyt** [comment]
> thanks caleb, can you `npm install @algora/sdk@v0.1.3-beta.0` to see if this resolved your issue?

@zcesur, I'm still facing this issue.

**Comment by zcesur** [comment]
awesome, just published a [new version](https://www.npmjs.com/package/@algora/sdk/v/0.1.3)! :pray:

**Comment by kaf-lamed-beyt** [comment]
Thank you, @zcesur! 🪔

**Pull request merged**
